# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import haas.protos.hist_pb2 as hist__pb2

GRPC_GENERATED_VERSION = '1.76.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in hist_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class HistogrammerStub(object):
    """The histogram service definition.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.fill = channel.unary_unary(
                '/Histogrammer/fill',
                request_serializer=hist__pb2.FillRequest.SerializeToString,
                response_deserializer=hist__pb2.Result.FromString,
                _registered_method=True)
        self.flush = channel.unary_unary(
                '/Histogrammer/flush',
                request_serializer=hist__pb2.FlushRequest.SerializeToString,
                response_deserializer=hist__pb2.Result.FromString,
                _registered_method=True)


class HistogrammerServicer(object):
    """The histogram service definition.
    """

    def fill(self, request, context):
        """Sends a filling request
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def flush(self, request, context):
        """Sends a flushing request
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_HistogrammerServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'fill': grpc.unary_unary_rpc_method_handler(
                    servicer.fill,
                    request_deserializer=hist__pb2.FillRequest.FromString,
                    response_serializer=hist__pb2.Result.SerializeToString,
            ),
            'flush': grpc.unary_unary_rpc_method_handler(
                    servicer.flush,
                    request_deserializer=hist__pb2.FlushRequest.FromString,
                    response_serializer=hist__pb2.Result.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'Histogrammer', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('Histogrammer', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class Histogrammer(object):
    """The histogram service definition.
    """

    @staticmethod
    def fill(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/Histogrammer/fill',
            hist__pb2.FillRequest.SerializeToString,
            hist__pb2.Result.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def flush(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/Histogrammer/flush',
            hist__pb2.FlushRequest.SerializeToString,
            hist__pb2.Result.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
